import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import  Link  from "next/link";
export default function Account() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TravElephant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br>
      </br>
      <div className="m-20">
      <h1>Account</h1>
      <Link href="/"><a>Hello</a></Link>
      </div>
      

      
    </div>
  )
}