import Head from 'next/head'
import Image from 'next/image'
import LoginForm from '../components/LoginForm'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TravElephant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <br></br>
      
     
      <div className='relative m-20'>
    
      <LoginForm />
      </div>
      
    </div>
  )
}